# Generated by Django 6.0.3 on 2026-03-25 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FocoEstimado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_foco', models.FloatField()),
                ('lon_foco', models.FloatField()),
                ('distancia_media_m', models.FloatField(blank=True, null=True)),
                ('residuo_medio_m', models.FloatField(blank=True, null=True)),
                ('n_observacoes', models.IntegerField()),
                ('nivel_confianca', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=6)),
                ('distancia_elevacao_m', models.FloatField(blank=True, null=True)),
                ('calculado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foco_estimado', to='observacoes.grupo')),
            ],
            options={
                'verbose_name': 'Foco Estimado',
                'verbose_name_plural': 'Focos Estimados',
                'ordering': ['-calculado_em'],
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('azimute', models.FloatField()),
                ('elevacao', models.FloatField(blank=True, null=True)),
                ('precisao_gps', models.FloatField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=512, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observacoes', to='observacoes.grupo')),
            ],
            options={
                'verbose_name': 'Observação',
                'verbose_name_plural': 'Observações',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_json', models.JSONField()),
                ('gerado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado', models.BooleanField(default=False)),
                ('foco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='observacoes.focoestimado')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
    ]
