# Generated by Django 6.0.4 on 2026-04-26 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observacoes', '0008_diagrama_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='observacoes_tipo_ac_5d3c14_idx',
            old_name='audit_acao_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='observacoes_usuario_4e88a0_idx',
            old_name='audit_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='observacoes_objeto__481716_idx',
            old_name='audit_obj_idx',
        ),
        migrations.AddField(
            model_name='observacao',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacao',
            name='occurrence_type',
            field=models.CharField(blank=True, choices=[('fogo', 'Fogo'), ('fumaca', 'Fumaça')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='observacao',
            name='severity_level',
            field=models.IntegerField(blank=True, help_text='Severidade de 0 (mínimo) a 10 (máximo). 0–3 baixo, 4–6 médio, 7–10 alto.', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='angulo_min_graus',
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='dist_media_alto_m',
            field=models.FloatField(default=5000.0),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='min_obs_alto',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='min_obs_medio',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='raio_confianca_alto_m',
            field=models.FloatField(default=500.0),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='raio_confianca_baixo_m',
            field=models.FloatField(default=3000.0),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='raio_confianca_medio_m',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='raio_espacial_km',
            field=models.FloatField(default=3.0, help_text='Raio máximo (km) para agrupar observações no espaço.'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='residuo_alto_m',
            field=models.FloatField(default=500.0),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='residuo_medio_m',
            field=models.FloatField(default=500.0),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='altitude_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='clima',
            field=models.CharField(blank=True, max_length=100, verbose_name='Clima'),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='direcao_vento',
            field=models.CharField(blank=True, max_length=20, verbose_name='Direção do vento'),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='relevo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relevo'),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='vegetacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vegetação'),
        ),
        migrations.AlterField(
            model_name='detalhesambientais',
            name='velocidade_vento',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidade do vento (km/h)'),
        ),
        migrations.AlterField(
            model_name='focoestimado',
            name='calculado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Calculado em'),
        ),
        migrations.AlterField(
            model_name='focoestimado',
            name='lat',
            field=models.FloatField(verbose_name='Latitude do foco'),
        ),
        migrations.AlterField(
            model_name='focoestimado',
            name='lon',
            field=models.FloatField(verbose_name='Longitude do foco'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='dist_pontos_interesse',
            field=models.JSONField(blank=True, default=dict, help_text='Dicionário {ponto_id: distancia_m} com a distância do foco a cada ponto de interesse cadastrado.'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='distancia_media_m',
            field=models.FloatField(blank=True, help_text='Distância média dos observadores ao foco estimado.', null=True, verbose_name='Distância média (m)'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='elevacao_distance_m',
            field=models.FloatField(blank=True, help_text='Distância estimada pelo ângulo de pitch da câmera.', null=True, verbose_name='Distância por elevação (m)'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='n_observacoes',
            field=models.IntegerField(blank=True, help_text='Total de observações usadas na triangulação.', null=True, verbose_name='Nº de observações'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='residuo_medio_m',
            field=models.FloatField(blank=True, help_text='Desvio médio das retas de visada ao ponto estimado.', null=True, verbose_name='Resíduo médio (m)'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='severity_media',
            field=models.FloatField(blank=True, help_text='Média da severidade (0–10) das observações do grupo.', null=True),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='azimute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontodeinteresse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='objeto_tipo',
            field=models.CharField(blank=True, help_text='Ex: Observacao, Grupo, FocoEstimado, Usuario', max_length=64),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='tipo_acao',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTRO', 'Registro de conta'), ('ESQUECI_SENHA', 'Solicitacao de reset de senha'), ('SENHA_REDEFINIDA', 'Senha redefinida'), ('SENHA_ALTERADA', 'Senha alterada'), ('PERFIL_ALTERADO', 'Perfil alterado'), ('OBSERVACAO_CRIADA', 'Observacao criada'), ('OBSERVACAO_DELETADA', 'Observacao deletada'), ('GRUPO_CRIADO', 'Grupo criado'), ('GRUPO_REPROCESSADO', 'Grupo reprocessado'), ('GRUPO_CONCLUIDO', 'Grupo processado com sucesso'), ('GRUPO_ERRO', 'Erro ao processar grupo'), ('CONFIG_ALTERADA', 'Configuracao do sistema alterada'), ('ACAO_ADMIN', 'Acao administrativa'), ('OUTRO', 'Outro')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='usuario_str',
            field=models.CharField(blank=True, help_text='Username salvo no momento da acao (mesmo se usuario deletado depois).', max_length=64),
        ),
    ]
