# Generated by Django 6.0.3 on 2026-04-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_telefone_username_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador da Central'), ('USUARIO', 'Usuário')], default='USUARIO', max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
